[package]
name = "venv-wrapper"
version = "0.1.0"
authors = ["Nicolas Marier <software@nmarier.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "~2.33.3", features=["color"]}
eyre = "~0.6.3"
simple-eyre = "~0.3"
termcolor = "~1.1"
directories = "~3.0.1"
config = "~0.10.1"
serde = { version = "~1.0", features = ["derive"] }
toml = "~0.5"
