[package]
name = "venv-wrapper"
version = "0.1.2"
authors = ["Nicolas Marier <software@nmarier.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Simple python virtual environment management"
homepage = "https://github.com/marier-nico/venv-wrapper"
repository = "https://github.com/marier-nico/venv-wrapper"
readme = "README.md"
keywords = ["cli", "python", "venv", "virtualenv"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
ansi_term = "~0.12.1"
clap = { version = "~2.33.3", features=["color"]}
config = "~0.10.1"
directories = "~3.0.1"
eyre = "~0.6.3"
quale = "~1.0"
serde = { version = "~1.0", features = ["derive"] }
simple-eyre = "~0.3"
spinners = "~1.2.0"
toml = "~0.5"
