# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
on: [push, pull_request]

name: Build and Lint

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('.github/workflows/build.yml') }}
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
      - run: python -m pip install pre-commit
      - run: SKIP=no-commit-to-branch pre-commit run --color always --from-ref origin/main --to-ref HEAD
